### ISSUE TITLE
Have something like "honorable mentions"

### ISSUE THREAD

**Issue by Ben-PH** [jonatasbaldin/awesome-awesome-awesome#1]
Navigating this list-stack is pretty straight forward, especially if you know the sort of thing you are looking for. A .md, perhaps in the README, dedicated to drawing attention to parts that you would unlikely go looking for.

One hypothetical example might be in a heakel list, it goes into formal verification, which might be interesting to people that might not otherwise find themselves there.

This issue submitted on mobile. If the fedback is along the lines of "i like it" im happy to put a bit of work into a pull request.

**Comment by jonatasbaldin** [comment]
hey, how are you doing?

I read this a couple of times, but didn't get what u meant :< can u elaborate?
